version: "3.3"

networks:
  outer-gateway:
    external: true
  internal:
    external: false

services:
  traefik:
    image: traefik:v2.0
    restart: always
    container_name: traefik
    ports:
      - "80:80" # <== http
      - "8080:8080" # <== :8080 is where the dashboard runs on
      - "443:443" # <== https
    volumes:
#      - ./letsencrypt:/letsencrypt # <== Volume for certs (TLS)
      - /var/run/docker.sock:/var/run/docker.sock # <== Volume for docker admin
      - ./traefik/dynamic.yaml:/dynamic.yaml # <== Volume for dynamic conf file, **ref: line 27
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./traefik/ssl/__meowalien_com.crt:/__meowalien_com.crt
      - ./traefik/ssl/__meowalien_com.key:/__meowalien_com.key
    networks:
      - outer-gateway # <== Placing traefik on the network named web, to access containers on this network
#    labels:
#      #### Labels define the behavior and rules of the traefik proxy for this container ####
#      - "traefik.enable=true" # <== Enable traefik on itself to view dashboard and assign subdomain to view it
#      - "traefik.http.routers.api.rule=Host(`traefik_dashboard.meowalien.com`)" # <== Setting the domain for the dashboard
#      - "traefik.http.routers.api.service=api@internal" # <== Enabling the api to be a service to access


  web:
    image: rabbitgather/web
    container_name: rabbitgather_web
    build: services/web
    depends_on:
      - traefik
      - mysql
      - neo4j
#    ports:
#      - "800:80" # <== http

    networks:
      - outer-gateway
      - internal
    labels:
      #### Labels define the behavior and rules of the traefik proxy for this container ####
      - "traefik.enable=true" # <== Enable traefik to proxy this container
      - "traefik.http.routers.rabbitgather-web.rule=Host(`web.meowalien.com`)" # <== Your Domain Name goes here for the http rule
      - "traefik.http.routers.rabbitgather-web.tls=true"
      - "traefik.http.routers.rabbitgather-web.entrypoints=https" # <== Defining the entrypoint for http, **ref: line 30
      - "traefik.docker.network=outer-gateway"
      - "traefik.http.services.rabbitgather-web.loadbalancer.server.port=443"


  mysql:
    image: mysql:v8.0
    build: ./mysql
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/initdb:/docker-entrypoint-initdb.d
      - ./mysql/datadir:/var/lib/mysql
      - ./mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      MYSQL_ROOT_PASSWORD: 31fmk#%#^%r2^u83r#@
    restart: always
    networks:
      - internal

  neo4j:
    image: neo4j:4.3.3-community
    ports:
      - "7687:7687"
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/plugins
    environment:
      NEO4J_AUTH: neo4j/nET@F*MVGreojoisdh0ri9r2eo4j_rwofj
    restart: always
    networks:
      - internal
