version: "3.3"

services:
  traefik:
    container_name: rabbitgather-traefik
    image: traefik:v2.0
    ports:
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/dynamic.yaml:/dynamic.yaml
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      #     SSL憑證
      - ./traefik/ssl/meowalien.com/cert.pem:/cert.pem
      - ./traefik/ssl/meowalien.com/privkey.pem:/privkey.pem

    restart: always

  nginx:
    container_name: rabbitgather-nginx
    ports:
      - "8888:80"
    depends_on:
      - traefik
    image: nginx:1.20.1
    volumes:
      - ./web:/web
      - ./nginx/conf.d:/etc/nginx/conf.d
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.rabbitgather-web.loadbalancer.server.port=80"
      - "traefik.http.routers.rabbitgather-web.rule=Host(`rabbit_gather_web.meowalien.com`)"
      - "traefik.http.routers.rabbitgather-web.tls=true"
      - "traefik.http.routers.rabbitgather-web.entrypoints=https"
    restart: always

  mariadb:
    container_name: rabbitgather-mariadb
    build: ./mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mariadb/datadir:/var/lib/mysql
      - ./mariadb/initdb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    restart: always

  redisdb:
    container_name: rabbitgather-redisdb
    image: redis:6.2.5
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    restart: always

  #  核心
  core:
    container_name: rabbitgather-core
    ports:
      - "2001:2001"
    build:
      context: api/core
    environment:
      DEBUG: "true"
    volumes:
      - ./api/core/config/config_docker.json:/app/config/config.json
      - ./api/core/log/:/app/log/
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.rabbitgather-core.loadbalancer.server.port=2001"
      - "traefik.http.routers.rabbitgather-core.rule=Host(`rabbit_gather_api.meowalien.com`)"
      - "traefik.http.routers.rabbitgather-core.tls=true"
      - "traefik.http.routers.rabbitgather-core.entrypoints=https"
    depends_on:
      - redisdb
      - mariadb
      - traefik