api:
  insecure: true
  dashboard: true
  debug: true

log:
  level: DEBUG

providers:
  docker:
    watch: true
    exposedbydefault: false
    network: outer-gateway
  file:
    filename: /dynamic.yaml
entryPoints:
  http:
    address: :80
  https:
    address: :443



